apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-app
  namespace: demo

spec:
  replicas: 3

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app

    spec:
      imagePullSecrets:
        - name: ghcr-creds

      containers:
        - name: demo-app
          image: ghcr.io/redkiy88/demo-app:1.0.0

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"