// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: geoip/geoip.proto

package geoip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_geoip_geoip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{1}
}

func (x *LookupResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *LookupResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *LookupResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LookupResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_geoip_geoip_proto protoreflect.FileDescriptor

const file_geoip_geoip_proto_rawDesc = "" +
	"\n" +
	"\x11geoip/geoip.proto\x12\x05geoip\"\x1f\n" +
	"\rLookupRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"x\n" +
	"\x0eLookupResponse\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude2E\n" +
	"\fGeoIPService\x125\n" +
	"\x06Lookup\x12\x14.geoip.LookupRequest\x1a\x15.geoip.LookupResponseB6Z4github.com/dmitriimoskin/geo-weather-app/proto/geoipb\x06proto3"

var (
	file_geoip_geoip_proto_rawDescOnce sync.Once
	file_geoip_geoip_proto_rawDescData []byte
)

func file_geoip_geoip_proto_rawDescGZIP() []byte {
	file_geoip_geoip_proto_rawDescOnce.Do(func() {
		file_geoip_geoip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoip_geoip_proto_rawDesc), len(file_geoip_geoip_proto_rawDesc)))
	})
	return file_geoip_geoip_proto_rawDescData
}

var file_geoip_geoip_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_geoip_geoip_proto_goTypes = []any{
	(*LookupRequest)(nil),  // 0: geoip.LookupRequest
	(*LookupResponse)(nil), // 1: geoip.LookupResponse
}
var file_geoip_geoip_proto_depIdxs = []int32{
	0, // 0: geoip.GeoIPService.Lookup:input_type -> geoip.LookupRequest
	1, // 1: geoip.GeoIPService.Lookup:output_type -> geoip.LookupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_geoip_geoip_proto_init() }
func file_geoip_geoip_proto_init() {
	if File_geoip_geoip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoip_geoip_proto_rawDesc), len(file_geoip_geoip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geoip_geoip_proto_goTypes,
		DependencyIndexes: file_geoip_geoip_proto_depIdxs,
		MessageInfos:      file_geoip_geoip_proto_msgTypes,
	}.Build()
	File_geoip_geoip_proto = out.File
	file_geoip_geoip_proto_goTypes = nil
	file_geoip_geoip_proto_depIdxs = nil
}
